### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by LuigiBaute** [GeheimagEnte/ImageResizeOpenCV#1]
Greetings, @GeheimagEnte 

I've noticed you're starting this project in this Open Source community!
I wanted to collaborate by delivering a _free_ logo proposal!
If that's something that may interest you, let me know!

I'm a Graphic Designer and an Open Source Enthusiast!
Cheers!
-Luigi.

**Comment by bluecater** [comment]
Hi GeheimagEnte, 

I read your code, but I didn't see where you using GPU in resize image processing?

Cheers!
Wei

**Comment by GeheimagEnte** [comment]
Hi Wei,
I don't. I intended to do so, but this was slower than on CPU. Fixed the comments where it was mentioned, thanks.
